# Generated by Django 5.0 on 2024-03-07 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(help_text='enter your full name', max_length=50)),
                ('emp_code', models.CharField(max_length=3)),
                ('mobile', models.BigIntegerField(unique=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.position')),
            ],
        ),
    ]
